---
name: Main

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - debian:
              - debian/10
              - debian/9
          - ubuntu:
              - ubuntu/20.04
              - ubuntu/18.04
    steps:
      - run: echo ${{ join(matrix.distro) }}
      - run: echo ${{ toJSON(matrix.distro) }}
